--- #YAML:1.0
name:                KiokuDB-Backend-BDB
version:             0.02
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    BerkeleyDB::Manager:           0.07
    Data::Stream::Bulk:            0
    KiokuDB:                       0
    Moose:                         0
    MooseX::Types::Path::Class:    0
    Search::GIN:                   0
    Storable:                      0
    Test::More:                    0
    Test::TempDir:                 0
    Test::use::ok:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
