--- #YAML:1.0
name:                KiokuDB-Backend-BDB
version:             0.01
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    BerkeleyDB:                    0.35
    BerkeleyDB::Manager:           0
    KiokuDB:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
